#!/usr/bin/env python3
"""Generate src/mod/Base.SC2Data/LibWoLUnbalancedGen.galaxy from the reference catalogs.

Reads the vanilla Liberty catalogs in mods/_reference/ and emits per-player
CatalogFieldValueModify calls implementing the global rules. Hand-written logic
stays in LibWoLUnbalanced.galaxy; this file owns only the generated apply-body.
"""
import os
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF = os.path.join(ROOT, "mods", "_reference")
OUT = os.path.join(ROOT, "src", "mod", "Base.SC2Data", "LibWoLUnbalancedGen.galaxy")

CATALOGS = ["mods/liberty.sc2mod", "campaigns/liberty.sc2campaign",
            "campaigns/libertystory.sc2campaign"]

# Player-faction units whose weapons get the rule-7 damage-point cap.
# Mercs/heroes get appended in a later batch once their ids are mapped.
PLAYER_UNITS = [
    "SCV", "Marine", "Medic", "Firebat", "Marauder", "Reaper", "Ghost", "Spectre",
    "Hellion", "Vulture", "Goliath", "Diamondback", "SiegeTank", "SiegeTankSieged",
    "Thor", "Predator", "Medivac", "Wraith", "VikingAssault", "VikingFighter",
    "Banshee", "Battlecruiser", "Raven", "ScienceVessel", "Hercules",
]

DAMAGE_POINT_CAP = 0.1
BUILD_TIME_CAP = 60.0
BUILD_TIME_OVERRIDES = {"Predator": 10.0, "Hercules": 20.0}

# Rule 8: free cloak — ability ids with an energy activation cost, and buff
# behaviors with an energy drain (negative regen). Extracted from the catalogs
# below; listed explicitly so the output is reviewable.
CLOAK_ABILS = ["GhostCloak", "BansheeCloak", "WraithCloak", "RogueGhostCloak",
               "DuskWingBansheeCloakingField", "SpectreCloak"]
CLOAK_BEHAVIORS = ["GhostCloak", "BansheeCloak", "WraithCloak", "SpectreCloaking",
                   "PredatorCloaking", "BansheeCloakCrossSpectrumDampeners"]


def load(catalog_file):
    """Yield (source, root) for each reference catalog that has this file."""
    for src in CATALOGS:
        path = os.path.join(REF, src, catalog_file)
        if os.path.exists(path):
            yield src, ET.parse(path).getroot()


def collect_weapons():
    """unit id -> weapon links (campaign catalog wins over mod catalog)."""
    unit_weapons = {}
    for _, root in load("UnitData.xml"):
        for unit in root.iter("CUnit"):
            uid = unit.get("id")
            if uid not in PLAYER_UNITS:
                continue
            links = [w.get("Link") for w in unit.findall("WeaponArray") if w.get("Link")]
            if links:
                unit_weapons[uid] = links  # later catalogs override
    return unit_weapons


def weapon_damage_points():
    """weapon id -> explicit DamagePoint (None if not set => engine default 0.167)."""
    points = {}
    for _, root in load("WeaponData.xml"):
        for w in list(root.iter("CWeaponLegacy")) + list(root.iter("CWeaponStrafe")):
            wid = w.get("id")
            dp = w.find("DamagePoint")
            if wid:
                points[wid] = float(dp.get("value")) if dp is not None else points.get(wid)
    return points


def train_entries():
    """(abil id, index, unit, time) for all CAbilTrain entries, later catalogs win."""
    entries = {}
    for _, root in load("AbilData.xml"):
        for abil in root.iter("CAbilTrain"):
            aid = abil.get("id")
            for info in abil.findall("InfoArray"):
                idx = info.get("index")
                unit_el = info.find("Unit")
                unit = unit_el.get("value") if unit_el is not None else info.get("Unit")
                time = info.get("Time")
                if time is None:
                    t_el = info.find("Time")
                    time = t_el.get("value") if t_el is not None else None
                if idx and unit:
                    key = (aid, idx)
                    prev_time = entries.get(key, (None, None))[1]
                    entries[key] = (unit, float(time) if time else prev_time)
    return entries


def emit():
    lines = [
        "//==================================================================================================",
        "// GENERATED by scripts/genlib.py — do not edit by hand.",
        "//==================================================================================================",
        "",
        "void libWoLUGen_Apply (int p) {",
    ]

    lines.append("    // --- Marines: +20 base HP (unit-table) ---")
    for f in ("LifeMax", "LifeStart"):
        lines.append(f'    CatalogFieldValueModify(c_gameCatalogUnit, "Marine", "{f}", p, "20", c_upgradeOperationAdd);')

    lines.append("")
    lines.append("    // --- Rule 8: free cloak (no activation cost, no energy drain) ---")
    for a in CLOAK_ABILS:
        lines.append(f'    CatalogFieldValueModify(c_gameCatalogAbil, "{a}", "Cost[0].Vital[Energy]", p, "0", c_upgradeOperationSet);')
    for b in CLOAK_BEHAVIORS:
        lines.append(f'    CatalogFieldValueModify(c_gameCatalogBehavior, "{b}", "Modification.VitalRegenArray[Energy]", p, "0", c_upgradeOperationSet);')

    lines.append("")
    lines.append("    // --- Rule 7: damage point (attack windup) cap at 0.1 s ---")
    unit_weapons = collect_weapons()
    points = weapon_damage_points()
    seen = set()
    for uid in PLAYER_UNITS:
        for wid in unit_weapons.get(uid, []):
            if wid in seen:
                continue
            seen.add(wid)
            dp = points.get(wid)
            if dp is None or dp > DAMAGE_POINT_CAP:
                lines.append(f'    CatalogFieldValueModify(c_gameCatalogWeapon, "{wid}", "DamagePoint", p, "{DAMAGE_POINT_CAP}", c_upgradeOperationSet);  // {uid}, was {dp if dp is not None else "default 0.167"}')

    lines.append("")
    lines.append("    // --- Rule 5: build time cap 60 s (+ explicit overrides) ---")
    for (aid, idx), (unit, time) in sorted(train_entries().items()):
        target = BUILD_TIME_OVERRIDES.get(unit)
        if target is None and time is not None and time > BUILD_TIME_CAP:
            target = BUILD_TIME_CAP
        if target is not None and time != target:
            lines.append(f'    CatalogFieldValueModify(c_gameCatalogAbil, "{aid}", "InfoArray[{idx}].Time", p, "{target}", c_upgradeOperationSet);  // {unit}, was {time}')

    lines.append("}")
    lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    emit()
