#!/usr/bin/env python3
"""Preview lens — turn the per-player CatalogFieldValueModify edits into a machine-
verified buff manifest, and gate them on the no-op field classes (CHECK8).

This is "lever 1 + lever 2" of docs/verification-ledger.md. The shipped galaxy library
(src/mod/Base.SC2Data/LibWoLUnbalancedGen.galaxy, generated by genlib.py) contains every
per-player edit as a line:

    CatalogFieldValueModify(c_gameCatalog<Kind>, "<id>", "<field>", p, "<value>", c_upgradeOperation<Op>);  // <comment>

We PARSE that file (no genlib changes → shipped galaxy stays byte-identical) to get the
canonical edit list, then for each edit:
  1. classify the field into GOOD / NOOP / UNCERTAIN (recipe docs/examples/02-no-op-traps.md),
  2. resolve the vanilla base value from mods/_reference/ (best-effort; '?' if too gnarly),
  3. compute the buffed final (base then op value),
  4. emit a human-readable buff manifest + a stdout summary.

Two modes:
  preview.py            — write build/preview/buff-manifest.md + print summary (NON-failing).
  preview.py --check    — CHECK8: exit non-zero if ANY edit is NOOP or UNRESOLVED (typo id /
                          field that resolves to no real entry). UNCERTAIN is a WARN, not a fail.

Stdlib-only; Windows-safe (forces UTF-8 stdout/stderr — the console is cp1252).
"""
import os
import re
import sys
import xml.etree.ElementTree as ET

# Windows: the default console codepage (cp1252) can't encode the non-ASCII glyphs we
# print (→ ✓ — ×), raising UnicodeEncodeError. Force UTF-8 stdout/stderr (mirrors audit.py).
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF = os.path.join(ROOT, "mods", "_reference")
GD = os.path.join(ROOT, "src", "mod", "Base.SC2Data", "GameData")
GALAXY = os.path.join(ROOT, "src", "mod", "Base.SC2Data", "LibWoLUnbalancedGen.galaxy")
OUT_DIR = os.path.join(ROOT, "build", "preview")
OUT_MANIFEST = os.path.join(OUT_DIR, "buff-manifest.md")

# Catalog layers loaded by a WoL campaign map, in merge order (later wins) — same precedence
# as genlib.CATALOGS. Base resolution walks these for a unit/abil/weapon/effect/behavior id.
CATALOGS = ["mods/liberty.sc2mod", "campaigns/liberty.sc2campaign",
            "campaigns/libertystory.sc2campaign"]
# The "c_gameCatalog<Kind>" token in the galaxy line -> the reference XML file that holds it.
KIND_FILE = {
    "Unit": "UnitData.xml",
    "Abil": "AbilData.xml",
    "Weapon": "WeaponData.xml",
    "Effect": "EffectData.xml",
    "Behavior": "BehaviorData.xml",
}

# A line in the generated lib. The trailing comment (after //) is optional.
EDIT_RE = re.compile(
    r'CatalogFieldValueModify\(\s*c_gameCatalog(\w+)\s*,\s*'
    r'"([^"]*)"\s*,\s*'          # entry id
    r'"([^"]*)"\s*,\s*'          # field path
    r'p\s*,\s*'
    r'"([^"]*)"\s*,\s*'          # value (may be empty)
    r'c_upgradeOperation(\w+)\s*\)\s*;'   # op
    r'(?:\s*//\s*(.*))?$'        # optional comment
)


# ----------------------------------------------------------------------------------------
# Field classification (recipe docs/examples/02-no-op-traps.md is the authority).
# ----------------------------------------------------------------------------------------
# A per-player CatalogFieldValueModify applies ONLY to scalar / indexed-scalar / nested-scalar
# fields. It silently no-ops on: indexed-ARRAY *elements* on effects (AttributeBonus[Light]),
# *.Link fields, string fields (TargetFilters, *.Requirements), and load-time CargoSize.

GOOD = "GOOD"
NOOP = "NOOP"
UNCERTAIN = "UNCERTAIN"


def classify(kind, field):
    """Return (klass, note). klass in {GOOD, NOOP, UNCERTAIN}."""
    f = field

    # --- NOOP: documented dead per-player edits (recipe 02 trap table) ---
    # Unit CargoSize — read once at bunker LOAD time; the runtime edit never reaches it.
    if kind == "Unit" and f == "CargoSize":
        return NOOP, "load-time field (bunker reads CargoSize when loading) → runtime edit never reaches it"
    # Effect indexed-ARRAY element — CatalogFieldValueModify can't create/replace array entries.
    if kind == "Effect" and re.match(r"AttributeBonus\[", f):
        return NOOP, "indexed-array element on an effect — runtime edit can't replace array entries"
    # Link fields anywhere (AbilArray[i].Link, WeaponArray[i].Link, ...).
    if re.search(r"\bLink$", f) or re.search(r"\]\.Link\b", f):
        return NOOP, "*.Link field — runtime LINK edits are silent no-ops (XML index-override instead)"
    # Requirement-LINK field on a train button.
    if re.search(r"\.Button\.Requirements$", f) or f.endswith(".Requirements") or f == "Requirements":
        return NOOP, "requirement-LINK field — per-player runtime link edits don't apply (use a clone / TechTree)"
    # String fields: TargetFilters (and SearchFilters / any *Filters string).
    if f == "TargetFilters" or f.endswith(".TargetFilters") or f.endswith("Filters"):
        return NOOP, "string field — per-player string-field edits don't apply (bake into a clone)"

    # --- UNCERTAIN: indexed-ish but GAME-confirmed working, or anything unplaced ---
    # The free-cloak energy-drain edit. It targets an indexed VitalRegenArray element, which
    # by the recipe-02 rule would be a no-op — BUT free cloak is GAME-confirmed working
    # (learnings.md §free cloak). The Cost[0].Vital[Energy] cloak-cost edits below ARE good
    # (scalar Cost). Mark only the regen-array edit UNCERTAIN with a note.
    if kind == "Behavior" and re.search(r"VitalRegenArray\[", f):
        return UNCERTAIN, ("indexed regen-array element (recipe-02 would call this a no-op) but free "
                           "cloak is GAME-confirmed working — keep, re-verify if cloak drain ever returns")

    # --- GOOD: per-player scalar / indexed-scalar / nested-scalar that applies ---
    # Plain unit scalars.
    UNIT_SCALARS = {
        "LifeMax", "LifeStart", "LifeArmor", "LifeRegenRate", "Sight", "Speed", "Food",
        "EnergyMax", "EnergyStart", "EnergyRegenRate", "ShieldsMax", "ShieldsStart",
    }
    if kind == "Unit" and f in UNIT_SCALARS:
        return GOOD, ""
    # Unit indexed-scalar cost (CostResource[Minerals] / [Vespene]) — an indexed SCALAR, applies.
    if kind == "Unit" and re.match(r"CostResource\[", f):
        return GOOD, ""
    # Weapon scalars.
    WEAPON_SCALARS = {"DamagePoint", "Period", "Backswing", "Range", "AllowedMovement"}
    if kind == "Weapon" and f in WEAPON_SCALARS:
        return GOOD, ""
    # Effect scalars.
    if kind == "Effect" and f in ("Amount", "ArmorReduction"):
        return GOOD, ""
    # Behavior scalar.
    if kind == "Behavior" and f == "Duration":
        return GOOD, ""
    # Abil scalars + nested/indexed scalars that apply per player.
    if kind == "Abil":
        if f in ("Range", "MaxCargoCount", "MaxCargoSize", "TotalCargoSpace"):
            return GOOD, ""
        # ability energy cost — nested scalar Cost[0].Vital[Energy].
        if re.match(r"Cost\[\d+\]\.Vital\[", f):
            return GOOD, ""
        # InfoArray[Train*/Research*].{Time, Charge.*, Cooldown.*} — nested scalars, apply.
        if re.match(r"InfoArray\[(Train|Research)\w*\]\.(Time|Charge\.\w+|Cooldown\.\w+)$", f):
            return GOOD, ""

    return UNCERTAIN, "field shape not in the GOOD/NOOP tables — confirm it's a per-player scalar"


# ----------------------------------------------------------------------------------------
# Base-value resolution (best-effort: '?' when the shape is too gnarly).
# ----------------------------------------------------------------------------------------
def _roots(kind):
    """Yield XML roots for this catalog kind, in merge order (later wins): the reference
    layers first, then OUR static GameData last (highest precedence — mirrors the real
    catalog merge, so our *WoLU / Merc* clones and any field we override are resolvable)."""
    fn = KIND_FILE.get(kind)
    if not fn:
        return
    for src in CATALOGS:
        p = os.path.join(REF, src, fn)
        if os.path.exists(p):
            try:
                yield ET.parse(p).getroot()
            except ET.ParseError:
                continue
    ours = os.path.join(GD, fn)
    if os.path.exists(ours):
        try:
            yield ET.parse(ours).getroot()
        except ET.ParseError:
            pass


def _find_elems(kind, entry_id):
    """ALL <C* id=entry_id> elements across the merge layers, in order (earlier→later).
    Returns [] if the id resolves to no entry anywhere (a typo)."""
    return [el for root in _roots(kind) for el in root if el.get("id") == entry_id]


def _parent_of(elems):
    """The parent= declared by any layer of this entry (later layers win)."""
    parent = None
    for el in elems:
        if el.get("parent"):
            parent = el.get("parent")
    return parent


def _scalar(el, name):
    """A plain scalar field: attribute form OR <Name value=...> child."""
    if el.get(name) is not None:
        return el.get(name)
    c = el.find(name)
    if c is not None and c.get("value") is not None:
        return c.get("value")
    return None


def _indexed(el, name, index):
    """An indexed scalar: <Name index="<index>" value=...> (e.g. CostResource[Minerals])."""
    for c in el.findall(name):
        if c.get("index") == index:
            return c.get("value")
    return None


def _field_from(el, field):
    """Extract a field value from ONE element, or None if unset/unhandled-shape on it."""
    # plain scalar: LifeMax, Range, Amount, Period, Duration, AllowedMovement...
    if re.match(r"^[A-Za-z]\w*$", field):
        return _scalar(el, field)

    # indexed scalar: Name[Index]  (CostResource[Minerals], AttributeBonus[Light])
    m = re.match(r"^([A-Za-z]\w*)\[([^\]]+)\]$", field)
    if m:
        return _indexed(el, m.group(1), m.group(2))

    # ability cost: Cost[0].Vital[Energy]  -> <Cost><Vital index="Energy" value=.../></Cost>
    m = re.match(r"^Cost\[(\d+)\]\.Vital\[([^\]]+)\]$", field)
    if m:
        costs = el.findall("Cost")
        idx = int(m.group(1))
        return _indexed(costs[idx], "Vital", m.group(2)) if idx < len(costs) else None

    # InfoArray[Train*/Research*].<...>  — Time is an attr on the InfoArray element;
    # nested Charge.*/Cooldown.* are sub-element scalars.
    m = re.match(r"^InfoArray\[([^\]]+)\]\.(.+)$", field)
    if m:
        info = next((ia for ia in el.findall("InfoArray") if ia.get("index") == m.group(1)), None)
        if info is None:
            return None
        sub = m.group(2)
        if sub == "Time":
            return _scalar(info, "Time")
        parts = sub.split(".")  # Charge.CountMax / Cooldown.TimeStart
        if len(parts) == 2:
            child = info.find(parts[0])
            if child is not None:
                if child.get(parts[1]) is not None:   # attr form <Charge CountMax="3"/>
                    return child.get(parts[1])
                return _scalar(child, parts[1])         # child form <CountMax value=.../>
        return None

    # Modification.VitalRegenArray[Energy] -> <Modification><VitalRegenArray index=.../></Modification>
    m = re.match(r"^Modification\.([A-Za-z]\w*)\[([^\]]+)\]$", field)
    if m:
        mod = el.find("Modification")
        return _indexed(mod, m.group(1), m.group(2)) if mod is not None else None

    return None  # shape unhandled on this element


def resolve_base(kind, entry_id, field, _seen=None):
    """Best-effort vanilla base for (kind, entry, field), resolving across merge layers and
    up the parent= chain (so our parent="Ghost" merc clones resolve their inherited base).
    Returns (base_str_or_None, exists_bool):
      - exists False => the id resolves to NO catalog entry anywhere (ref or ours) => a typo.
      - base None / exists True => the entry exists but the field is unset (engine default)
        or its shape is too gnarly — recorded as '?' (the manifest still classifies it)."""
    if _seen is None:
        _seen = set()
    if entry_id in _seen:          # parent cycle guard
        return None, True
    _seen.add(entry_id)

    elems = _find_elems(kind, entry_id)
    if not elems:
        return None, False         # UNRESOLVED — genuine typo / dead id

    # Later layers win: scan our-XML-last → reference order reversed for the field value.
    for el in reversed(elems):
        v = _field_from(el, field)
        if v is not None:
            return v, True

    # Field not set on this entry — inherit from parent= (Merc* clones, etc.).
    parent = _parent_of(elems)
    if parent:
        base, _ = resolve_base(kind, parent, field, _seen)
        if base is not None:
            return base, True

    return None, True              # exists, but field unset / shape unhandled → '?'


def compute_final(base, op, value):
    """Apply op(base, value) numerically when possible; else None."""
    try:
        b = float(base)
        v = float(value)
    except (TypeError, ValueError):
        return None
    if op == "Set":
        return v
    if op == "Add":
        return b + v
    if op == "Subtract":
        return b - v
    if op == "Multiply":
        return b * v
    return None


def fmt_num(x):
    """Trim trailing .0 for readability (65.0 -> 65, 1.4444 stays)."""
    if x is None:
        return "?"
    if isinstance(x, float):
        if x == int(x):
            return str(int(x))
        return f"{x:g}"
    return str(x)


# ----------------------------------------------------------------------------------------
# --mod : emit a LOADABLE static-global preview .SC2Mod so the buffed numbers are visible
# directly in the SC2 Editor's Data module. This is GLOBAL (no per-player gate) and NEVER
# shipped/played — purely a "read the numbers in the editor" lens. It writes the COMPUTED
# FINAL of each emittable GOOD edit as a static field override onto the vanilla id.
# ----------------------------------------------------------------------------------------
MOD_DIR = os.path.join(OUT_DIR, "WoLUnbalanced-Preview.SC2Mod")
# DocumentInfo dependency — IDENTICAL to the shipped mod (build/Mods/.../DocumentInfo) so
# base units (Marine/Thor/...) resolve when the editor loads this preview mod.
PREVIEW_DEPENDENCY = "bnet:Liberty (Mod)/0.0/999,file:Mods/Liberty.SC2Mod"


def _override_value_string(edit):
    """The string to write into the static override's value="" for this GOOD edit.

    For a numeric edit we emit the COMPUTED FINAL (resolve_base + compute_final). For a
    non-numeric Set (e.g. AllowedMovement="Moving") the final IS the literal value. Returns
    None when the value can't be computed safely (base unknown / non-Set non-numeric op) —
    the caller SKIPS such edits (partial coverage is fine for a lens; never emit a guess)."""
    if edit["final"] is not None:                      # numeric base + op -> computed final
        return fmt_num(edit["final"])
    # No numeric final. A Set writes its literal value REGARDLESS of the (unknown) base —
    # it's the only op whose result doesn't depend on base, so it's always safe to emit
    # without resolving base (numeric Set like Range=6 / ArmorReduction=0, OR a string-enum
    # Set like AllowedMovement="Moving"). Add/Subtract/Multiply DO need base -> skip those.
    if edit["op"] == "Set" and edit["value"] != "":
        return edit["value"]
    return None


def _set_scalar(parent, name, value):
    """Set a plain scalar child <Name value=...> under parent (create or update)."""
    child = parent.find(name)
    if child is None:
        child = ET.SubElement(parent, name)
    child.set("value", value)
    return child


def _set_indexed(parent, name, index, value):
    """Set an indexed-scalar child <Name index=.. value=..> (match on index, else create)."""
    for c in parent.findall(name):
        if c.get("index") == index:
            c.set("value", value)
            return c
    c = ET.SubElement(parent, name)
    c.set("index", index)
    c.set("value", value)
    return c


def _ensure_indexed_container(parent, name, index):
    """Find-or-create an indexed container child <Name index=..>...</Name> (for InfoArray)."""
    for c in parent.findall(name):
        if c.get("index") == index:
            return c
    c = ET.SubElement(parent, name)
    c.set("index", index)
    return c


def _ensure_child(parent, name):
    """Find-or-create a plain (un-indexed) container child <Name>...</Name> (Cost/Charge/...)."""
    c = parent.find(name)
    if c is None:
        c = ET.SubElement(parent, name)
    return c


def apply_override(el, field, value):
    """Write `field = value` onto element `el` as the INVERSE of preview.py._field_from.

    Builds/updates the right nested XML shape (verified against the reference catalogs):
      plain scalar          LifeMax                       -> <LifeMax value=..>
      indexed scalar        CostResource[Vespene]         -> <CostResource index="Vespene" value=..>
      ability cost          Cost[0].Vital[Energy]         -> <Cost><Vital index="Energy" value=..></Cost>
      train/research time   InfoArray[Train6].Time        -> <InfoArray index="Train6"><Time value=..></InfoArray>
      charge/cooldown       InfoArray[Train1].Charge.CountMax
                                                          -> <InfoArray index="Train1"><Charge><CountMax value=..></Charge></InfoArray>
    Returns True if it emitted the field, False if the shape is unhandled (caller SKIPS)."""
    # plain scalar
    if re.match(r"^[A-Za-z]\w*$", field):
        _set_scalar(el, field, value)
        return True

    # indexed scalar: Name[Index]
    m = re.match(r"^([A-Za-z]\w*)\[([^\]]+)\]$", field)
    if m:
        _set_indexed(el, m.group(1), m.group(2), value)
        return True

    # ability cost: Cost[0].Vital[Energy]  (the [0] is the first <Cost> element)
    m = re.match(r"^Cost\[(\d+)\]\.Vital\[([^\]]+)\]$", field)
    if m:
        # Match the inverse of _field_from: index into the Nth <Cost> element. We only ever
        # emit index 0 (the only form genlib produces); create one <Cost> if absent.
        idx = int(m.group(1))
        costs = el.findall("Cost")
        if idx < len(costs):
            cost = costs[idx]
        elif idx == 0:
            cost = ET.SubElement(el, "Cost")
        else:
            return False                               # would need to fabricate gap entries
        _set_indexed(cost, "Vital", m.group(2), value)
        return True

    # InfoArray[Train*/Research*].<...>
    m = re.match(r"^InfoArray\[([^\]]+)\]\.(.+)$", field)
    if m:
        info = _ensure_indexed_container(el, "InfoArray", m.group(1))
        sub = m.group(2)
        if sub == "Time":
            _set_scalar(info, "Time", value)           # <Time value=..> (child form; _field_from
            return True                                #  reads attr-or-child, so this resolves)
        parts = sub.split(".")                         # Charge.CountMax / Cooldown.TimeStart
        if len(parts) == 2:
            container = _ensure_child(info, parts[0])   # <Charge> / <Cooldown>
            _set_scalar(container, parts[1], value)     # <CountMax value=..> (child form)
            return True
        return False

    return False                                       # any other shape: skip (no guess)


def _indent(elem, level=0):
    """Pretty-print an ElementTree in place (stdlib has ET.indent only on 3.9+; do it by hand
    so this runs on any Python the repo targets)."""
    pad = "\n" + "    " * level
    if len(elem):
        if not (elem.text and elem.text.strip()):
            elem.text = pad + "    "
        for i, child in enumerate(elem):
            _indent(child, level + 1)
            tail = pad + "    " if i < len(elem) - 1 else pad
            if not (child.tail and child.tail.strip()):
                child.tail = tail
    if level and not (elem.tail and elem.tail.strip()):
        elem.tail = pad


def emit_mod(edits):
    """Write build/preview/WoLUnbalanced-Preview.SC2Mod/. Returns a summary dict."""
    # Group emittable overrides by (kind -> id -> [(field, value, edit)]) IN EDIT ORDER so
    # multiple overrides on the same id merge into ONE <C.. id=..> element per catalog file.
    by_kind = {}                       # kind -> {entry_id: <C..> Element}
    classes = {}                       # (kind, entry_id) -> tag (resolved entry class)
    emitted = 0
    skipped = []                       # (edit, reason)
    covered_ids = {}                   # kind -> set(ids)

    for e in edits:
        # Only GOOD edits can be safely shown as a static field override; NOOP/UNCERTAIN
        # don't apply per player at all, UNRESOLVED is a typo. (Matches the brief: skip them.)
        if e["klass"] != GOOD:
            skipped.append((e, f"class {e['klass']} (does not apply / not a real field)"))
            continue
        if not e["exists"]:
            skipped.append((e, "id resolves to no vanilla entry"))
            continue
        val = _override_value_string(e)
        if val is None:
            reason = ("base unknown (?) for a non-Set op" if e["op"] != "Set"
                      else "value not computable")
            skipped.append((e, reason))
            continue
        # Resolve the entry's catalog class from the merged element(s).
        elems = _find_elems(e["kind"], e["entry"])
        tag = elems[-1].tag if elems else None
        if not tag:
            skipped.append((e, "could not resolve entry class"))
            continue
        kid = (e["kind"], e["entry"])
        classes[kid] = tag
        cel = by_kind.setdefault(e["kind"], {}).get(e["entry"])
        if cel is None:
            cel = ET.Element(tag)
            cel.set("id", e["entry"])
            by_kind[e["kind"]][e["entry"]] = cel
        if apply_override(cel, e["field"], val):
            emitted += 1
            covered_ids.setdefault(e["kind"], set()).add(e["entry"])
        else:
            skipped.append((e, f"field shape unhandled for emit: {e['field']}"))
            # leave the (possibly empty) element; drop it later if it has no children

    # Build the mod folder.
    base_gd = os.path.join(MOD_DIR, "Base.SC2Data", "GameData")
    os.makedirs(base_gd, exist_ok=True)

    files_written = []
    for kind, ents in by_kind.items():
        root = ET.Element("Catalog")
        wrote_any = False
        for entry_id, cel in ents.items():
            if len(cel) == 0:          # no override actually emitted onto it -> drop
                continue
            root.append(cel)
            wrote_any = True
        if not wrote_any:
            continue
        _indent(root)
        fn = KIND_FILE[kind]
        path = os.path.join(base_gd, fn)
        tree = ET.ElementTree(root)
        with open(path, "wb") as f:
            f.write(b'<?xml version="1.0" encoding="utf-8"?>\n')
            tree.write(f, encoding="utf-8", xml_declaration=False)
            f.write(b"\n")
        files_written.append(path)

    # ComponentList.SC2Components — same shape as the built mod (gada auto-discovers the
    # GameData/*.xml; info rounds out the document). We DROP the built mod's `text` component:
    # this lens emits no GameText, so declaring one would point at an absent component. Written
    # CRLF to byte-match the built mod's structural files (SC2 tolerates either ending here).
    comp_path = os.path.join(MOD_DIR, "ComponentList.SC2Components")
    with open(comp_path, "w", encoding="utf-8", newline="\r\n") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n'
                '<Components>\n'
                '    <DataComponent Type="gada">GameData</DataComponent>\n'
                '    <DataComponent Type="info">DocumentInfo</DataComponent>\n'
                '</Components>\n')
    # DocumentInfo — the SAME single dependency the built mod declares (CRLF, byte-identical).
    info_path = os.path.join(MOD_DIR, "DocumentInfo")
    with open(info_path, "w", encoding="utf-8", newline="\r\n") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n'
                '<DocInfo>\n'
                '    <Dependencies>\n'
                f'        <Value>{PREVIEW_DEPENDENCY}</Value>\n'
                '    </Dependencies>\n'
                '</DocInfo>\n')

    # Validate: every emitted GameData xml must parse cleanly.
    parse_errors = []
    for path in files_written:
        try:
            ET.parse(path)
        except ET.ParseError as ex:
            parse_errors.append((path, str(ex)))
    for path in (comp_path, info_path):
        try:
            ET.parse(path)
        except ET.ParseError as ex:
            parse_errors.append((path, str(ex)))

    return {
        "emitted": emitted,
        "ids": sum(len(s) for s in covered_ids.values()),
        "covered_ids": covered_ids,
        "files": files_written + [comp_path, info_path],
        "gamedata_files": files_written,
        "skipped": skipped,
        "parse_errors": parse_errors,
        "by_kind": by_kind,
    }


def run_mod(edits):
    """`--mod` entrypoint: emit the preview mod + print the summary. Returns process code."""
    s = emit_mod(edits)

    # Top skip reasons.
    reasons = {}
    for _e, r in s["skipped"]:
        # collapse field-specific reasons to a stable bucket for the histogram
        key = re.sub(r": .*$", "", r)
        reasons[key] = reasons.get(key, 0) + 1

    print(f"preview --mod: wrote {os.path.relpath(MOD_DIR, ROOT)}")
    print(f"  {s['emitted']} overrides across {s['ids']} ids in "
          f"{len(s['gamedata_files'])} GameData file(s); {len(s['skipped'])} skipped")
    for kind, ids in sorted(s["covered_ids"].items()):
        print(f"    {KIND_FILE[kind]:16} {len(ids):3} ids")
    if reasons:
        print("  skip reasons:")
        for r, n in sorted(reasons.items(), key=lambda kv: -kv[1]):
            print(f"    {n:4}  {r}")
    if s["parse_errors"]:
        for path, msg in s["parse_errors"]:
            print(f"  FAIL XML parse: {os.path.relpath(path, ROOT)}: {msg}")
        print("  one or more emitted files are not well-formed — FAIL.")
        return 1
    print("  all emitted XML parses cleanly.")
    print(f"  load it: SC2 Editor -> Open -> {os.path.relpath(MOD_DIR, ROOT)} (Data module shows the finals)")
    return 0


def parse_edits():
    """Parse the generated galaxy lib into a list of edit dicts."""
    if not os.path.exists(GALAXY):
        raise SystemExit(f"preview: generated lib not found: {GALAXY}\n"
                         f"  run `python scripts/genlib.py` first.")
    edits = []
    for line in open(GALAXY, encoding="utf-8"):
        m = EDIT_RE.search(line)
        if not m:
            continue
        kind, entry, field, value, op, comment = m.groups()
        edits.append({"kind": kind, "entry": entry, "field": field,
                      "value": value, "op": op, "comment": (comment or "").strip()})
    return edits


def enrich(edits):
    """Add classification + base/final/exists to each edit.

    Stacked ops on the SAME (kind,id,field) are threaded CUMULATIVELY in emission order
    (= the order the lib applies them at runtime), so e.g. Firebat LifeMax `Multiply 2`
    then `Add 100` reads base → 2·base → 2·base+100 (the true runtime final), not last-wins.
    Each edit's `base` becomes its INPUT (vanilla base on the first edit of a group, the
    previous edit's final after that), so a manifest row shows that edit's input → output."""
    ref_present = os.path.exists(os.path.join(REF, "mods", "liberty.sc2mod", "UnitData.xml"))
    for e in edits:
        e["klass"], e["note"] = classify(e["kind"], e["field"])
        if ref_present:
            base, exists = resolve_base(e["kind"], e["entry"], e["field"])
            e["exists"] = exists
            e["base"] = base
        else:
            e["exists"] = True   # can't check without the dump; don't false-fail CHECK8
            e["base"] = None
    # Thread cumulative finals within each (kind,id,field) group, in file (= runtime) order.
    running = {}
    for e in edits:
        if e["base"] is None:
            e["final"] = None
            continue
        key = (e["kind"], e["entry"], e["field"])
        start = running.get(key, e["base"])   # vanilla base on the first edit; prev final after
        e["base"] = start                      # display each edit as its own input -> output
        e["final"] = compute_final(start, e["op"], e["value"])
        if e["final"] is not None:
            running[key] = e["final"]
    return ref_present


def manifest_rows(edits):
    """Render each edit as a manifest row string: kind | id | field | op value | base → final | comment."""
    rows = []
    for e in edits:
        base = fmt_num(e["base"]) if e["base"] is not None else "?"
        final = fmt_num(e["final"]) if e["final"] is not None else "?"
        opval = f"{e['op']} {e['value']}" if e["value"] != "" else f"{e['op']} (empty)"
        bf = f"{base} → {final}"
        rows.append((e["klass"], e["kind"], e["entry"], e["field"], opval, bf, e["comment"]))
    return rows


def write_manifest(edits, ref_present):
    os.makedirs(OUT_DIR, exist_ok=True)
    by = {GOOD: [], NOOP: [], UNCERTAIN: []}
    unresolved = []
    for e in edits:
        if not e["exists"]:
            unresolved.append(e)
        by[e["klass"]].append(e)

    lines = ["# Buff manifest — per-player CatalogFieldValueModify edits",
             "",
             "Generated by `scripts/preview.py` from the canonical edit list in",
             "`src/mod/Base.SC2Data/LibWoLUnbalancedGen.galaxy` (genlib output). Each row is one",
             "per-player edit, classified by whether the field class *applies* per player.",
             "",
             f"- **Total edits:** {len(edits)}",
             f"- **GOOD** (per-player scalar applies): {len(by[GOOD])}",
             f"- **NOOP** (documented no-op class → needs a static clone): {len(by[NOOP])}",
             f"- **UNCERTAIN** (verify): {len(by[UNCERTAIN])}",
             f"- **UNRESOLVED** (id resolves to no vanilla entry — typo): {len(unresolved)}",
             ""]
    if not ref_present:
        lines += ["> reference dump (mods/_reference/) absent — base→final values are '?' and the",
                  "> UNRESOLVED/typo check is skipped (runs in the local pre-commit gate).", ""]

    def section(title, items):
        out = [f"## {title} ({len(items)})", "",
               "| kind | id | field | op value | base → final | comment |",
               "|---|---|---|---|---|---|"]
        for e in items:
            base = fmt_num(e["base"]) if e["base"] is not None else "?"
            final = fmt_num(e["final"]) if e["final"] is not None else "?"
            opval = f"{e['op']} {e['value']}" if e["value"] != "" else f"{e['op']} (empty)"
            note = e["note"]
            comment = e["comment"]
            tail = comment + (f" — _{note}_" if note else "")
            out.append(f"| {e['kind']} | {e['entry']} | `{e['field']}` | {opval} | "
                       f"{base} → {final} | {tail} |")
        out.append("")
        return out

    if unresolved:
        lines += section("UNRESOLVED — id resolves to NO vanilla entry (likely typo)", unresolved)
    lines += section("GOOD — per-player scalar applies", by[GOOD])
    lines += section("NOOP — documented no-op field class (route through a static clone)", by[NOOP])
    lines += section("UNCERTAIN — verify field shape", by[UNCERTAIN])

    with open(OUT_MANIFEST, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    return by, unresolved


def main():
    check = "--check" in sys.argv
    mod = "--mod" in sys.argv
    edits = parse_edits()
    ref_present = enrich(edits)

    # --mod is a SEPARATE emit path: build the loadable static-global preview .SC2Mod and
    # return. It does NOT write the manifest or run CHECK8 (plain/--check behavior unchanged).
    if mod:
        if not ref_present:
            print("preview --mod: reference dump (mods/_reference/) absent — cannot resolve "
                  "base values / entry classes. Run from a checkout with the dump present.")
            return 1
        return run_mod(edits)

    by, unresolved = write_manifest(edits, ref_present)

    # Summary to stdout.
    print(f"preview: parsed {len(edits)} per-player edits from {os.path.relpath(GALAXY, ROOT)}")
    print(f"  GOOD {len(by[GOOD])} | NOOP {len(by[NOOP])} | "
          f"UNCERTAIN {len(by[UNCERTAIN])} | UNRESOLVED {len(unresolved)}")
    print(f"  manifest: {os.path.relpath(OUT_MANIFEST, ROOT)}")
    if not ref_present:
        print("  (reference dump absent — base→final '?' and UNRESOLVED check skipped)")

    if not check:
        # Non-failing mode: still surface UNCERTAIN as a WARN so it's visible.
        for e in by[UNCERTAIN]:
            print(f"WARN UNCERTAIN {e['kind']} {e['entry']} {e['field']} — {e['note']}")
        return 0

    # --check (CHECK8): FAIL on any NOOP or UNRESOLVED edit; UNCERTAIN is WARN only.
    for e in by[UNCERTAIN]:
        print(f"WARN UNCERTAIN {e['kind']} {e['entry']} \"{e['field']}\" — {e['note']}")
    failed = False
    for e in unresolved:
        failed = True
        print(f"FAIL CHECK8 UNRESOLVED {e['kind']} '{e['entry']}' field '{e['field']}' resolves "
              f"to no vanilla entry — typo? verify the id letter-by-letter.")
    for e in by[NOOP]:
        failed = True
        print(f"FAIL CHECK8 NOOP {e['kind']} '{e['entry']}' field '{e['field']}' is a known no-op "
              f"field class ({e['note']}) — route through a static clone "
              f"(see docs/examples/02-no-op-traps.md).")
    if failed:
        print(f"\nCHECK8: {len(unresolved)} unresolved + {len(by[NOOP])} no-op edit(s) — FAIL.")
        return 1
    print("\nCHECK8: ok — every runtime edit sits on a verified-applying field class.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
